[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
solana_hello_world = "8LyUD5qQzYLBYPVa4JYBm4GapUffLg9MGfQuJwCEQWtR"

[programs.devnet]
solana_hello_world = "8LyUD5qQzYLBYPVa4JYBm4GapUffLg9MGfQuJwCEQWtR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
